# ****************************************************************************
#
# Language configuration
#
# See:  https://gohugo.io/content-management/multilingual/
#
en:
  description: "Dedicated to restoring and preserving the Interlisp experience"
  languageName: English"
  # Weight used for sorting.
  weight: 1
  contentDir: content/en