# ****************************************************************************
#
# Language configuration
#
# See:  https://gohugo.io/content-management/multilingual/
#
en:
  languageName: English"
  # Weight used for sorting.
  weight: 1
  contentDir: content/en
  params:
    description: "Dedicated to restoring and preserving the Interlisp experience"