baseURL: https://stumbo.github.io/InterlispDraft.github.io/

# canonifyURLs: Convert relative URLs to absolute URLs
#   Enable for staging to map to appropriate baseURL
canonifyURLs: true
relativeURLs: true

languageCode: en-us
title: 'Staging Environment'
#publishDir: stage
