baseURL: https://interlisp.github.io/Interlisp.staging/

languageCode: en-us

# title
#  Insert Staging Environment onto every page to make clear
#  this is not the production site
title: 'Staging Environment'
