# add cache to 'vendor' for speeding up builds
cache:
  paths: 
    - vendor/

stages:
  - build
  - test
  - deploy

build_site:
  image: ruby:2.7
  stage: build
  before_script:
    - bundle config set path 'vendor'
    - bundle install
  script:
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public # generating site folder to be browsed or download
  except:
    - master # all branches expect 'master'

check:
  image: cyb3rjak3/html5validator
  stage: test
  script:
    - tests/html_validate_test
  except:
    - master # all branches expect 'master'

# 'pages' is a specially-named job that will deploy and build your site to the
# 'public' path to GitLab Pages.
pages:
  image: ruby:2.7
  stage: deploy
  before_script:
    - bundle config set path 'vendor'
    - bundle install
  script:
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch

