stages:
  - build
  - test
  - deploy

build_site:
  image:
    name: klakegg/hugo:ext-alpine
    # https://github.com/klakegg/docker-hugo/issues/13#issuecomment-678304121
    entrypoint: [""]
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - public # generating site folder to be browsed or download
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENV: production

check:
  image: cyb3rjak3/html5validator
  stage: test
  script:
    - tests/html_validate_test

# 'pages' is a specially-named job that will deploy and build your site to the
# 'public' path to GitLab Pages.
pages:
  image:
    name: klakegg/hugo:ext-alpine
    # https://github.com/klakegg/docker-hugo/issues/13#issuecomment-678304121
    entrypoint: [""]
  stage: deploy
  script:
    # https://github.com/klakegg/docker-hugo/issues/41#issuecomment-805607666
    - apk add --update brotli
    - hugo
    # https://docs.gitlab.com/ee/user/project/pages/introduction.html#serving-compressed-assets
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - main # this job will affect only the 'main' branch
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENV: production

