# ****************************************************************************
# 
# Services Configuration
#
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
googleAnalytics:
    id: G-JXK20KN1W1