name:  Update Zotero bibliography file

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 1"

jobs:
  update_zotero_bib_json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Run script file
        run: |
          chmod +x ./scripts/update_bibliography.sh
          ./scripts/update_bibliography.sh 
        shell: bash

      - name: Check for updates and push if needed
        run: |
          if [[ -n $(git status --short data/bibliography.json) ]]; then 
            git config --global user.name 'GitHub Action'
            git config --global user.email 'no.one@users.noreply.github.com'
            git commit -am "Updated Bibliography"
            git push
          fi
